"""create users table

Revision ID: 187845ce1fb2
Revises: fc7274ce6f67
Create Date: 2026-02-10 15:13:02.306298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187845ce1fb2'
down_revision = 'fc7274ce6f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
