"""add business_profiles table

Revision ID: 40937aad5f82
Revises: 243bec43a636
Create Date: 2026-03-31 21:32:46.941225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40937aad5f82'
down_revision = '243bec43a636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('target_audience', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('logo_base64', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
