"""add description to generated_content

Revision ID: 51b535687829
Revises: c0150823b0a4
Create Date: 2026-04-15 16:06:10.493955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b535687829'
down_revision = 'c0150823b0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
