"""add selection_count to brand_memory

Revision ID: 7405063c4585
Revises: efda5222d8aa
Create Date: 2026-04-16 16:23:20.260049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7405063c4585'
down_revision = 'efda5222d8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selection_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.drop_column('selection_count')

    # ### end Alembic commands ###
