"""add preferred_creativity to brand_memory

Revision ID: 8b7c21767f1a
Revises: 51b535687829
Create Date: 2026-04-15 16:35:21.166366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7c21767f1a'
down_revision = '51b535687829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_creativity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.drop_column('preferred_creativity')

    # ### end Alembic commands ###
