"""Add GeneratedContent model

Revision ID: a7401fbd1541
Revises: 187845ce1fb2
Create Date: 2026-02-11 15:26:12.035208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7401fbd1541'
down_revision = '187845ce1fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_content')
    # ### end Alembic commands ###
