"""add learned VAD to brand_memory

Revision ID: efda5222d8aa
Revises: 8b7c21767f1a
Create Date: 2026-04-16 15:40:30.349999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efda5222d8aa'
down_revision = '8b7c21767f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learned_valence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('learned_arousal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('learned_dominance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.drop_column('learned_dominance')
        batch_op.drop_column('learned_arousal')
        batch_op.drop_column('learned_valence')

    # ### end Alembic commands ###
