"""create ping table

Revision ID: fc7274ce6f67
Revises: 
Create Date: 2026-02-06 15:13:39.846090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7274ce6f67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ping')
    # ### end Alembic commands ###
