import os
from openai import OpenAI

# Create OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def generate_marketing_text(
    business_name: str,
    industry: str,
    target_audience: str,
    tone: str,
    platform: str,
    description: str = "",
    goal: str = "",
    region: str = "UK",
    length: str = "short"
) -> str:
    """
    Generates AI marketing text based on business input.
    """

    # Decide output length
    length_instruction = {
        "short": "1–2 sentences",
        "medium": "3–4 sentences"
    }.get(length.lower(), "1–2 sentences")

    # Build the prompt
    prompt = f"""


You are a highly skilled AI marketing assistant specialising in small and medium-sized businesses (SMEs).
You understand how to create engaging, practical, and platform-appropriate marketing content that helps
businesses connect with their audience without sounding corporate or overly technical.

TASK:
Write a {length_instruction} marketing caption specifically for {platform}.

BUSINESS CONTEXT:
- Business name: {business_name}
- Industry: {industry}
- Description: {description}
- Target audience: {target_audience}
- Primary marketing goal: {goal if goal else "Increase engagement"}
- Desired tone: {tone}
- Target region or market: {region}

CONTENT GUIDELINES:
- Use clear, simple language that is easy to understand.
- Avoid technical jargon or complex marketing terms.
- Write in a friendly, human, and natural style.
- Make the content suitable for a small business rather than a large corporation.
- Ensure the caption feels authentic and relatable to the target audience.

REGIONAL & CULTURAL ADAPTATION:
- Tailor spelling, phrasing, and expressions to suit the target region.
- Reflect culturally appropriate communication styles for the region.
  - For example, UK audiences may prefer friendly but understated language.
  - US audiences may respond well to more enthusiastic and direct messaging.
  - Other regions should be approached respectfully and naturally.
- Avoid slang, references, or expressions that would feel unfamiliar or inappropriate for the region.
- Ensure the message sounds natural to someone living in the target market.

PLATFORM-SPECIFIC RULES:
- Adapt the writing style to suit {platform}.
- For Instagram or Facebook:
  - Keep the tone conversational and engaging.
  - Emojis may be used sparingly if they suit the tone.
- For LinkedIn:
  - Maintain a professional yet approachable tone.
  - Avoid emojis unless explicitly appropriate.
- For Twitter/X:
  - Be concise and impactful.
  - Focus on a single clear message.
- For general platforms:
  - Keep the message clear and easy to skim.

STRUCTURE REQUIREMENTS:
- Start with an engaging opening line that captures attention.
- Clearly communicate the value or benefit offered by the business.
- Align the message with the stated marketing goal.
- End with a subtle and natural call-to-action (e.g. visit, try, discover, learn more).

STYLE CONSTRAINTS:
- Do not use excessive punctuation or emojis.
- Do not add dashes (-) as punctuation.
- Do not exaggerate or make unrealistic claims.
- Avoid hashtags unless they are explicitly requested.
- Do not mention that this content was generated by AI.

OUTPUT FORMAT:
- Return only the final caption text.
- Do not include explanations, bullet points, or additional commentary.

QUALITY CHECK:
Before finalising the caption, ensure that:
- The tone matches the requested style.
- The content is culturally appropriate for the specified region.
- The content is relevant to the target audience.
- The message would make sense to a real customer encountering it on {platform}.
-- Target region or market: {region}
"""





    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You help small businesses create marketing content."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=150,
            temperature=0.7
        )

        return response.choices[0].message.content.strip()

    except Exception:
        return "Unable to generate content at this time."
